version: '3.8'

services:
  app:
    image: 'restjpa:latest'
    build:
      context: .
    depends_on:
      - db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/demo-db
      - DATASOURCE_USERNAME=dba
      - DATASOURCE_PASSWORD=secret
    ports:
      - "8088:8080"
    networks:
      - frontend
      - backend

  db:
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_USER=dba
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo-db
    volumes:
      - restjpa-pg-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  restjpa-pg-data:

networks:
  frontend:
    external: true
    name: restjpa_frontend
  backend:
