FROM maven:3.9.0-eclipse-temurin-17-focal

WORKDIR /app
COPY pom.xml ./
RUN mvn dependency:resolve
COPY src ./src

RUN mvn clean verify

CMD mvn --quiet exec:java -Dexec.mainClass="fr.univtln.bruno.demos.docker.App"
# CMD java -jar target/*-jar-with-dependencies.jar
# CMD java -cp target/*-jar-with-dependencies.jar fr.univtln.bruno.demos.docker.App