FROM maven:3.9.0-eclipse-temurin-17-focal as stage-build
WORKDIR /app
COPY pom.xml ./
RUN mvn dependency:resolve
COPY src ./src
RUN mvn clean verify

FROM eclipse-temurin:17-jre-jammy
COPY --from=stage-build /app/target/*-jar-with-dependencies.jar /myapp.jar
CMD ["java","-jar","/myapp.jar"]
