name: 'Make and publish books'

on:  push

jobs:
  makebooks:
    # The tags on the runner
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building books
        run: ./makeBooks.sh
        shell: bash
      - name: Archive book
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            .book/_build/singlehtml/README.html            

